#!/bin/sh

# Abort if any command returns an error value
set -e

case "$1" in
	configure)
	if [ -f "/lib/systemd/system/mariadb.service" ]; then
		sed -i -e "s/LimitNOFILE=16364/LimitNOFILE=32000/g" /lib/systemd/system/mariadb.service;
                systemctl daemon-reload
	fi
    	if [ -f "/etc/mysql/conf.d/centreon.cnf" ]; then
        	systemctl restart mysql
    	fi
    	;;

	abort-upgrade|abort-remove|abort-deconfigure)
    	;;

	*)
    	echo "$0: called with unknown argument" 1>&2
    	exit 0
    	;;
esac

exit 0
