#!/bin/sh

# Abort if any command returns an error value
set -e

case "$1" in
	configure)
    	if [ -f "/usr/share/centreon/bin/centcore" ]; then
        	chown centreon:centreon /usr/share/centreon/bin/centcore
    	fi

    	if [ -f "/lib/systemd/system/centcore.service" ]; then
        	systemctl daemon-reload
        	systemctl enable centcore.service
    	fi

    	if [ -d "/var/lib/centreon" ]; then
        	chmod 775 /var/lib/centreon
    	fi

    	;;

	abort-upgrade|abort-remove|abort-deconfigure)
    	;;

	*)
    	echo "$0: called with unknown argument" 1>&2
    	exit 0
    	;;
esac

exit 0 	 

