#!/bin/sh

# Abort if any command returns an error value
set -e

case "$1" in
	configure)
    	if [ -f "/etc/mysql/conf.d/innodb.cnf" ]; then
        	service mysql restart
    	fi
    	;;

	abort-upgrade|abort-remove|abort-deconfigure)
    	;;

	*)
    	echo "$0: called with unknown argument" 1>&2
    	exit 0
    	;;
esac

exit 0
