#!/bin/sh

# Abort if any command returns an error value
set -e

case "$1" in
	remove|upgrade|deconfigure)
    	if [ -f "/etc/init.d/sudo" ]; then
       	service sudo reload
    	fi
    	;;

	failed-upgrade)
    	;;

	*)
    	echo "$0: called with unknown argument" 1>&2
    	exit 0
    	;;
esac

exit 0
